theme = "dracula"
icons = "awesome5"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "toggle"
text = "HDMI"
command_state = "xrandr"
command_on = "~/.screenlayout/hdmi.sh"
command_off = "~/.screenlayout/vga.sh"
interval = 5



[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}"
format_swap = "{swap_used}/{swap_total}"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1
format = "{utilization}"

[[block]]
block = "music"
max_width= 14
smart_trim=true
player = "spotify"
buttons = ["prev", "play", "next"]

[[block]]
block = "net"
device = "eno1"
format = "{speed_down;K*b} {speed_up;K*b}"
interval = 5

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %I:%M %p"
